apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: 881490114708.dkr.ecr.eu-north-1.amazonaws.com/my-web-app:latest
          ports:
            - containerPort: 80
